- 👋 Hi, I’m @Lokesh-sankholiya
- 👀 I’m interested in Full Stack Development
- 🌱 I’m currently learning C/DSA/OS/OOPS...
- 💞️ I’m looking to collaborate on Frontend developer
- 📫 How to reach me - This is my mail id : sankholiyalokesh@gmail.com 
- ⚡ Fun fact: The 'box-shadow' CSS property was inspired by design elements in Apple's Mac OS. First implemented by WebKit, it adds drop shadows to elements, enhancing web design aesthetics.
